src/Entity/Rules.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RulesRepository")
 */
class Rules
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $abstract;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\Column(type="date")
     */
    private $publishing_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $end_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAbstract(): ?string
    {
        return $this->abstract;
    }

    public function setAbstract(?string $abstract): self
    {
        $this->abstract = $abstract;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getPublishingDate(): ?\DateTimeInterface
    {
        return $this->publishing_date;
    }

    public function setPublishingDate(\DateTimeInterface $publishing_date): self
    {
        $this->publishing_date = $publishing_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }
}

src/Form/RulesType.php
<?php

namespace App\Form;

use App\Entity\Rules;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RulesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('abstract')
            ->add('description')
            ->add('pays')
            ->add('publishing_date')
            ->add('end_date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Rules::class,
        ]);
    }
}

src/Controller/RulesController.php
<?php

namespace App\Controller;

use App\Entity\Rules;
use App\Form\RulesType;
use App\Repository\RulesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/rules")
 */
class RulesController extends AbstractController
{
    /**
     * @Route("/", name="rules_index", methods={"GET"})
     */
    public function index(RulesRepository $rulesRepository): Response
    {
        return $this->render('rules/index.html.twig', [
            'rules' => $rulesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="rules_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $rule = new Rules();
        $form = $this->createForm(RulesType::class, $rule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rule);
            $entityManager->flush();

            return $this->redirectToRoute('rules_index');
        }

        return $this->render('rules/new.html.twig', [
            'rule' => $rule,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="rules_show", methods={"GET"})
     */
    public function show(Rules $rule): Response
    {
        return $this->render('rules/show.html.twig', [
            'rule' => $rule,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="rules_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Rules $rule): Response
    {
        $form = $this->createForm(RulesType::class, $rule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('rules_index');
        }

        return $this->render('rules/edit.html.twig', [
            'rule' => $rule,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="rules_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Rules $rule): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rule->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($rule);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rules_index');
    }
}

templates/rules/_delete_form.html.twig
<form method="post" action="{{ path('rules_delete', {'id': rule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rule.id) }}">
    <button class="btn">Delete</button>
</form>

templates/rules/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/rules/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Rules{% endblock %}

{% block body %}
    <h1>Edit Rules</h1>

    {{ include('rules/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('rules_index') }}">back to list</a>

    {{ include('rules/_delete_form.html.twig') }}
{% endblock %}

templates/rules/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rules index{% endblock %}

{% block body %}
    
<style>
    /* ##################################
    #               BASICS              #
    #                                   #
    ##################################### */
        p {
            margin: 0;
        }

    
    /* ##################################
    #    HEADER (Menu + titre)          #
    #                                   #
    ##################################### */
        header {
            display:flex;
            align-items: center;
            margin: 30px 0 30px;
        }
        h1 {
            text-align: center;
            margin: 0;
            font-family: "DunbarLow";
            text-transform: uppercase;
            font-size: 22px;
            letter-spacing: 2px;
            flex-grow: 1;
        }
        header span {
            display: block;
            width: 20px;
        }

    /* #################################
       #   Cards                       #
       ################################# */
    main {
        margin-top: 50px;
    }
    .rule {
        background: #fff;
        border-radius: 10px;
        box-shadow: 0 6px 8px rgba(0,0,0,.16);
        margin-bottom: 20px;
        padding: 10px 20px 20px;
        display: flex;
    }
    .rule_info {
        display: flex;
        flex-direction: column;
        width: 10px;
        flex-grow: 1;
        margin-right: 10px;
    }
    .rule_title {
        font-family: "Futura";
        font-size: 20px;
        line-height: 20px;
        margin-bottom: 5px;
    }
    .rule_description {
        font-weight: 200;
        font-size: 16px;
        flex-grow: 1;
        margin-bottom: 16px;
    }
    .rule_end {
        font-weight: 200;
        font-size: 16px;
        justify-self: flex-end;
    }
    .rule_img {
        width: 90px;
    }
    .rule_img img {
        width: 100%;
    }
</style>
    
<div class="container">
    <header>
        <!-- Menu Burger -->
        <span></span>
        <h1>Règles à suivre</h1>
        <div class="menu-wrap">
            <input type="checkbox" class="toggler">
            <div class="hamburger">
                <div></div>
            </div>
            <div class="menu">
                <div>
                    <div>
                        <ul>
                            <li><a href="{{ path('homepage') }}">Accueil</a></li>
                            <li><a href="{{ path('news_index') }}">Actualité</a></li>
                            <li><a href="{{ path('profil_user') }}">Profil</a></li>
                            <li><a href="{{ path('rules_index') }}">Règles à suivre</a></li>
                        </ul>
                        <img class="img_menu" src="{{ asset('assets/img/menu_burger_perso.png') }}">
                    </div>
                </div>
            </div>
        </div>
    </header>

    <main>
        {% for rule in rules %}
            <div class="rule">
                <div class="rule_info">
                    <p class="rule_title">{{ rule.title }}</p>
                    <p class="rule_description">{{ rule.description }}</p>
                    <p class="rule_end">Date de fin: {{ rule.endDate ? rule.endDate|date('Y-m-d') : 'indéfini' }}</p>
                </div>
                <div class="rule_img">
                    <img src="{{ asset('assets/img/rule_' ~ rule.id ~ '.png') }}">
                </div>
            </div>
            <!--
                <a href="{{ path('rules_show', {'id': rule.id}) }}">show</a>
                <a href="{{ path('rules_edit', {'id': rule.id}) }}">edit</a>
            -->
        {% else %}
            <p>Pas de rules enregistré</p>
        {% endfor %}
        <!-- Cards des rules -->
    </main>
    {# <a href="{{ path('rules_new') }}">Create new</a> #}
</div>

    
{% endblock %}

templates/rules/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Rules{% endblock %}

{% block body %}
    <h1>Create new Rules</h1>

    {{ include('rules/_form.html.twig') }}

    <a href="{{ path('rules_index') }}">back to list</a>
{% endblock %}

templates/rules/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rules{% endblock %}

{% block body %}
    <h1>Rules</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ rule.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ rule.title }}</td>
            </tr>
            <tr>
                <th>Abstract</th>
                <td>{{ rule.abstract }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ rule.description }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ rule.pays }}</td>
            </tr>
            <tr>
                <th>Publishing_date</th>
                <td>{{ rule.publishingDate ? rule.publishingDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End_date</th>
                <td>{{ rule.endDate ? rule.endDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('rules_index') }}">back to list</a>

    <a href="{{ path('rules_edit', {'id': rule.id}) }}">edit</a>

    {{ include('rules/_delete_form.html.twig') }}
{% endblock %}